# NOTE: Generated By HttpRunner v3.1.6
# FROM: api\web\py.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCasePy(HttpRunner):

    config = Config("testcase description")

    teststeps = [
        Step(
            RunRequest("/stdFee/pay.do")
            .post("http://bms.yzwill.cn/stdFee/pay.do")
            .with_headers(
                **{
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                    "sendTime": "1649334973077",
                    "title": "%E7%BC%B4%E8%B4%B9",
                    "transferId": "7418a416f2cb48a788541ba2a9be16a2",
                    "transferSeq": "1",
                    "uri": "http://bms.yzwill.cn/stdFee/toPay.do?learnId=164933358190966447",
                }
            )
            .with_data(
                {
                    "_web_token": "21785011477764691",
                    "accDeduction": "0.00",
                    "couponsStr": "[]",
                    "grade": "2022",
                    "itemCodes": "Y3",
                    "learnId": "164933358190966447",
                    "payData": '{"learnId":"164933358190966447","paymentType":"1","tradeType":"NATIVE","accDeduction":"0.00","zmDeduction":"0","coupons":"[]","items":"[{\\"orderNo\\":\\"7233421262414938345\\",\\"itemCode\\":\\"S1\\",\\"itemName\\":\\"代收第一年书费\\",\\"itemYear\\":\\"1\\",\\"amount\\":\\"20.00\\",\\"accScale\\":0,\\"zmScale\\":0,\\"couponScale\\":0,\\"payAmount\\":\\"20.00\\"},{\\"orderNo\\":\\"7233421262414938344\\",\\"itemCode\\":\\"Y1\\",\\"itemName\\":\\"代收第一年学费\\",\\"itemYear\\":\\"1\\",\\"amount\\":\\"20.00\\",\\"accScale\\":0,\\"zmScale\\":0,\\"couponScale\\":0,\\"payAmount\\":\\"20.00\\"},{\\"orderNo\\":\\"7233421262414938348\\",\\"itemCode\\":\\"S2\\",\\"itemName\\":\\"代收第二年书费\\",\\"itemYear\\":\\"2\\",\\"amount\\":\\"20.00\\",\\"accScale\\":0,\\"zmScale\\":0,\\"couponScale\\":0,\\"payAmount\\":\\"20.00\\"},{\\"orderNo\\":\\"7233421262414938346\\",\\"itemCode\\":\\"Y2\\",\\"itemName\\":\\"代收第二年学费\\",\\"itemYear\\":\\"2\\",\\"amount\\":\\"20.00\\",\\"accScale\\":0,\\"zmScale\\":0,\\"couponScale\\":0,\\"payAmount\\":\\"20.00\\"},{\\"orderNo\\":\\"7233421262414938349\\",\\"itemCode\\":\\"S3\\",\\"itemName\\":\\"代收第三年书费\\",\\"itemYear\\":\\"3\\",\\"amount\\":\\"20.00\\",\\"accScale\\":0,\\"zmScale\\":0,\\"couponScale\\":0,\\"payAmount\\":\\"20.00\\"},{\\"orderNo\\":\\"7233421262414938347\\",\\"itemCode\\":\\"Y3\\",\\"itemName\\":\\"代收第三年学费\\",\\"itemYear\\":\\"3\\",\\"amount\\":\\"20.00\\",\\"accScale\\":0,\\"zmScale\\":0,\\"couponScale\\":0,\\"payAmount\\":\\"20.00\\"}]","dataSources":"5","grade":"2022","payAmount":"120.00","remark":""}',
                    "payableCount": "120.00",
                    "paymentType": "1",
                    "remark": "",
                    "years": "3",
                    "zmDeduction": "0",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "E000039")
            .assert_equal("body.body", None)
            .assert_equal("body.msg", "非法操作")
            .assert_equal("body.ok", False)
        ),
    ]


if __name__ == "__main__":
    TestCasePy().test_start()
